#!/bin/bash
# install-nfs-server - Installs the network file system package. The script then starts and enables the service, and provides feedback to the user that it is done.
# CIT470
# Instructor: Darci Guriel
# Team: 5
# Membership: John Laycock, Jonathan Gaskill, Even Brodbeck
# Author: John Laycock

# Start installing nfs-utils
echo "Starting Network File System Install."
yum install nfs-utils 

# Finished nfs-utils, creating shared directory and chznge permissions
mkdir -p /var/nfs_share
chmod -R 755 /var/nfs_share

# Starting/enabling services
systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap
systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap

#Adding local network to allowed connections
echo "/var/nfs_share 10.2.6.0/23(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports

#Restart nfs service
systemctl restart nfs-server

#Add firewall rules
firewall-cmd --permanent --zone=public --add-service=nfs
firewall-cmd --permanent --zone=public --add-service=mountd
firewall-cmd --permanent --zone=public --add-service=rpc-bind
firewall-cmd --reload

#Share nfs folder
exportfs

echo "Network File System Installed, Configured, and Restarted."